name = "turquoise-server"
main = "src/index.js"
compatibility_date = "2024-01-01"

[vars]
NTFY_DEFAULT_TOPIC = "your-default-topic"
APNS_KEY_ID = ""
APNS_TEAM_ID = ""
APNS_TOPIC = ""

[[d1_databases]]
binding = "NOTIFICATION_DB"
database_name = "TurquoiseDB"
database_id = "96b9add9-6851-4161-8aa0-ab0347728228"
